name: CI

on:
  push:
    branches: ["master", "develop", "feature/**"]
  pull_request:
    branches: ["master", "develop", "feature/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build --if-present

      - name: Run unit tests
        run: npm run test
