name: Test Coverage

on:
  push:
    branches: ["master", "develop", "feature/**"]
  pull_request:
    branches: ["master", "develop", "feature/**"]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test coverage
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: simplecov
          result_path: coverage/coverage-final.json
          min_coverage: 90
          token: ${{ secrets.GITHUB_TOKEN }}
