name: Test Coverage

on:
  push:
    branches: ["master", "develop", "feature/**"]
  pull_request:
    branches: ["master", "develop", "feature/**"]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: devmasx/coverage-check-action@v1.2.0
      with:
        type: simplecov
        result_path: coverage/coverage-final.json
        min_coverage: 90
        token: ${{ secrets.GITHUB_TOKEN }}
